version: '3'

services:

  mysql1:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mysql
    ports:
      - 3306:3306
    volumes:
      - /home/hans/Escritorio/git_proyect/bd_spring_docker:/var/lib/mysql
    networks:
      - employee-mysql
      
  myapp-main:
    image: javadbapp
    networks:
      - employee-mysql
    restart: on-failure
    depends_on:
      - mysql1
    ports:
      - 80:8080
    environment:
      - DATABASE_HOST=mysql1
      - DATABASE_USER=root
      - DATABASE_PASSWORD=mysql
      - DATABASE_NAME=test
      - DATABASE_PORT=3306
   
networks:
  employee-mysql: 
